### ISSUE TITLE
signOutOfOkta function is not  part of OktaAuth (1.0.1) 

### ISSUE THREAD

**Issue by maheshm255** [okta/okta-sdk-appauth-ios#115]
I am doing Pod Install using "    pod "OktaAuth" which is  installing OktaAuth (1.0.1) which does not contains "signOutOfOkta" function , could you pls let me know how to get this signOutOfOkta(Logout)functionality .

**Comment by nbarbettini** [comment]
Hey @maheshm255, we are getting ready to publish the new version to Cocoapods. I merged the readme too soon (should have waited until after publishing). Sorry about that! I will leave this issue open until we publish it for real.

**Comment by maheshm255** [comment]
@nbarbettini , Thanks for update, Just checking when you are planning to release 2.0.0 , we have release planned next week and client is asking for signout functionality so it would be great if we can have this functionality ASAP, Also is there any way to invalidate okta session in 1.0.1 version, I have put "prompt = login" in plist to forcefully show okta login page , but it populate below screen and when I click singout and sigin again it doesn't redirect back to app instead it go inside OKTA apps as show in below screenshots
<img width="440" alt="a" src="https://user-images.githubusercontent.com/5462746/51318912-aaca5180-1a81-11e9-8475-a036a5c78180.png">
<img width="440" alt="b" src="https://user-images.githubusercontent.com/5462746/51318916-ac941500-1a81-11e9-8061-4060fa27b2bd.png">

**Comment by nbarbettini** [comment]
We have released 2.0.0: https://github.com/okta/okta-sdk-appauth-ios/releases/tag/2.0.0

Please open a new issue if you are still having issues! 👍
