### ISSUE TITLE
Got OktaAuth.OktaError.noTokens when refreshing token ?

### ISSUE THREAD

**Issue by gloryluu** [okta/okta-sdk-appauth-ios#119]
Hi, I got this issue while refreshing the token. I have checked that it already came through the function
`storeAuthState(_ tokenManager: OktaTokenManager)` when signin with browser. The weird thing is the access token is never saved to keychain. :/
You guy know how to fix it ?
Temporarily I have to refresh the token with Rest endpoint.

**Comment by codal-ashahu** [comment]
Hi, we are facing the same issue on 1.0.1 Release, any suggestions?

@gloryluu can you confirm if you are storing the refreshed token's in Okta Token Manager or handing it on your own?

**Comment by gloryluu** [comment]
@codal-ashahu: I'm handling it on my own logic included store and refresh token.

**Comment by nbarbettini** [comment]
Hey @codal-ashahu and @gloryluu, are you still experiencing this issue in 2.0? We made a number of improvements and bug fixes in the newest release.

**Comment by robertjd** [comment]
Closing issue for now, please re-open if this problem still exists
