### ISSUE TITLE
signOutOfOkta returning missingIdToken

### ISSUE THREAD

**Issue by gabehoffman** [okta/okta-sdk-appauth-ios#121]
What does `missingIdToken` mean as an error message? I'm having some trouble getting this function to work. It's not popping up a temp web view, so I'm pretty sure it's not working as intended, but I don't think I can pass it anything.

**Comment by nbarbettini** [comment]
Hey @gabehoffman, sorry for the delay. Can you show the code you're using for sign-in and sign-out? We'll investigate and figure out if there's a bug here.

**Comment by gabehoffman** [comment]
Thanks @nbarbettini, here's the code for sign in and sign out.

### Sign-in
```
    /// Get an authenticated login token from the Okta framework
    private func getOktaLoginToken(from viewController: UIViewController) -> Task<OktaTokenManager> {
        let oktaTokenManagerResult = Task<OktaTokenManager>.Promise()

        OktaAuth.signInWithBrowser().start(viewController)
            .then  { oktaTokenManager in oktaTokenManagerResult.fill(with: Task.Result(success: oktaTokenManager)) }
            .catch { error in oktaTokenManagerResult.fill(with: Task.Result(failure: error)) }

        return Task(oktaTokenManagerResult)
    }
```

### Sign-out
```
func performLogout() {

        OktaAuth.signOutOfOkta().start(self)
            .then {
                print("OKTA SUCCESS")
                LogoutUtils.doLogoutActivities()
                self.displayLoginErrorMessage()
            }
            .catch { error in
                error.logDebugError(context: "\(#function)", message: "signOutOfOkta failed - \(error)")
                self.errorReason = error
                throw error
        }
    }
```
Happy to pair with anyone as well. It's pretty much a cut and paste of the readme code samples. Sign-in works fine. Sign-out always give the `missingIdToken`

**Comment by anastasiiaiurok-okta** [comment]
Hi @gabehoffman !
The error “missingIdToken” means that we don’t have idToken available at the moment. That could mean that user is not authenticated or his tokens were not stored somehow after authentication.
Could you please provide more details on the issue so we could investigate it.
1. What is the order of calls of signIn and signOut? 
2. Do you call signOut within the same run where signIn happens? Or is it another run of the app?

**Comment by Preslma** [comment]
Hi @anastasiiaiurok-okta,

1a. We are calling `signInWithBrowser()` only when the user is completely logged out and needs to authenticate. Note we are using a custom authorizer and not the default one, says our Okta-minded colleague here. Also, we do not `signInWithBrowser` on each app launch and foreground. After the initial successful Okta login, we immediately exchange the Okta id_token and access_token with a custom OIDC server and leverage the latter tokens for our OAuth2 flows (we have a complicated permissions model for which we need the second server). When the user initiates a logout from the app, only then do we call `signOutOfOkta`.
1b. We do not yet leverage `revoke` or `clear` anywhere in our code or any other OktaAuth methods except for `resume`.
2. Based on what you said, it's obvious now that we only get 'missingIdToken' issue when the user has left the app and returned back after the original login. This is a use case we need to figure out how to handle if a requirement of logout is to have an idToken present in the keychain. However, I also wanted to point out that in the same run signIn -> signOut, we are also currently getting a redirect to a blank, full screen, webview that does not dismiss, so we are in an unrecoverable state there, too.

**Comment by anastasiiaiurok-okta** [comment]
@gabehoffman @Preslma Please, provide more details on how Sign Out method is initiated in your app. What view controller is passed? Is it presented at the moment when sign out is called?

**Comment by gabehoffman** [comment]
There was some sequencing issues that I think were causing the issue. It's resolved and it was on our end. Thanks for your help in diagnosing the problem.
