### ISSUE TITLE
PKCE not implemented?

### ISSUE THREAD

**Issue by babadofar** [okta/okta-sdk-appauth-ios#13]
Trying to login using code-supplied username + password, but it only works if I add the client_id and client_secret. Is PKCE implemented at all?

**Comment by omgitstom** [comment]
PKCE is implemented for authorization code flow, if you are using resource owner password grant it will not use PKCE.

**Comment by babadofar** [comment]
I imagined there was a way to have users enter credentials in a native dialog,that is: without opening Okta login screen in a browser, but apparently not.

**Comment by omgitstom** [comment]
That is definitely possible but isn't as secure as Authorization Code with PKCE. 

```
OktaAuth
    .login(username: "user@example.com", password: "password")
    .start(view: self) {
        response, error in
               
        if error != nil { print(error!) }
                
        // Success
        if let authResponse = response {
            // authResponse.accessToken
            // authResponse.idToken
        }
    }

```

This will require that you put the client secret in a plist, so you can not trust that the secret is secure going live with this model.  We do understand that there is a need to create a native experience, and not everyone will fit into the AppAuth / Safari Web View Controller model.

Out of curiousity, if Okta added the ability to fully customize the webpage that is shown, and the URL, would you still want to build a full native experience?

Thanks

**Comment by babadofar** [comment]
Yes, you're right, it would definitely help if it was possible to customize the URL and webpage :)

The API documentation may seem to indicate that it is possible to get a session token from the Authentication API and continue the Authorization Code Flow from there. But it does not work for me .
https://developer.okta.com/docs/api/resources/oauth2.html#obtain-an-authorization-grant-from-a-user
