### ISSUE TITLE
How to set authorization server 

### ISSUE THREAD

**Issue by babadofar** [okta/okta-sdk-appauth-ios#15]
I get errors validating tokens due to authentication does not happen against the authorization server for my app.
How can I set authorization server? 
Any chance this is fixed in pull request https://github.com/okta/okta-sdk-appauth-ios/pull/12 ?

**Comment by jmelberg-okta** [comment]
Hi @babadofar,

Just to verify, is the `issuer` in your `Okta.plist` configuration mapped to your authorization server?
For example, the issuer should be a value similar to:  
```
https://dev-123456.oktapreview.com/oauth2/{authorizationServerId}/
```

Also -- can you include the error response?

**Comment by jmelberg-okta** [comment]
@babadofar If this is still an issue, please feel free to reopen.
