### ISSUE TITLE
Unable to find a specification for `OktaAuth`

### ISSUE THREAD

**Issue by Touchcore** [okta/okta-sdk-appauth-ios#16]
After adding pod 'OktaAuth' to my podfile and running pod install, I get the following error message: 
Unable to find a specification for `OktaAuth`
![oktaauth pod error](https://user-images.githubusercontent.com/11425045/29933170-b714724c-8e44-11e7-9121-9953892940cd.png)

**Comment by jmelberg-okta** [comment]
Hi @Touchcore,

The pod is available on [Cocoapods registry](http://cocoapods.org/pods/OktaAuth), so make you've updated Cocoapods recently:
```
gem install cocoapods
```
