### ISSUE TITLE
Set clientSecret for okta-sdk programatically

### ISSUE THREAD

**Issue by skeer00** [okta/okta-sdk-appauth-ios#23]
We are integrating Okta into our mobile applications. We are following resource owner password flow and okta sdk (https://github.com/okta/okta-sdk-appauth-ios).

In the documentation (readme) it says that If using the Resource Owner Password Grant, you must specify the clientSecret in Okta.plist. But it also mention that IMPORTANT: It is strongly discouraged to store a clientSecret on a distributed app. Please refer to OAuth 2.0 for Native Apps for more information.

So how can we set/update the clientSecret from the code (programmatically)? I could not find any method to set clientSecret in the SDK.

If we are using okta.plist, the how to changed the endpoints, clientSecret etc for different environments?

**Comment by jmelberg-okta** [comment]
@skeer00: Currently there is no way to programmatically `set` or `update` the `clientSecret`. 

Instead, you can start the **login** flow using a different `plist` file containing different **client credentials**:

```swift
OktaAuth
  .login("user@example.com", password: "password")
  .start(withPListConfig: "Okta-PasswordFlow", view: self) { response, error in
    // do stuff
  }
```

Care to elaborate on your use case? As noted, this flow is only for [trusted clients](https://tools.ietf.org/html/rfc6749#section-2.1). Native applications are public clients and can not keep the `client_secret` secure.

**Comment by skeer00** [comment]
So you mean the native applications cannot keep clientSecret in the plist file too?

**Comment by jmelberg-okta** [comment]
My comment was directed more toward asking - Why are you using the client credentials (resource owner password credentials flow) as opposed to the authorization code flow grant? I'd strongly suggest reading [OAuth 2.0 for Native Apps](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-12) if you haven't already done so.

This library currently supports both flows and requires client configuration via a `plist` file. That implementation may change in the future. Regardless of where the `client_secret` is stored in a native app, it cannot be treated as a "secret". Per [OAuth 2.0 Thread Model + Security Considerations RFC-6819](https://tools.ietf.org/html/rfc6819#section-5.3.1):

> A secret, burned into the source code
   of the application or an associated resource bundle, cannot be
   protected from reverse engineering.  Secondly, such secrets cannot be
   revoked, since this would immediately put all installations out of
   work

**Comment by skeer00** [comment]
Thank you @jmaldonado-okta.

One more question, the "authorization code flow grant" is Proof Key for Code Exchange (PKCE) flow?

**Comment by jmelberg-okta** [comment]
@skeer00 The Proof Key for Code Exchange (PKCE) is a protocol building **on top** of the OAuth 2.0 Authorization Code Flow Grant. It was implemented as a technique to mitigate `code` interception attacks. The flow is essentially the same for the end-user, but requires a cryptographically random key called a `code verifier`. See the diagram below from the [PKCE](https://tools.ietf.org/html/rfc7636#section-1.1) spec:

> 1.1.  Protocol Flow

                                                 +-------------------+
                                                 |   Authz Server    |
       +--------+                                | +---------------+ |
       |        |--(A)- Authorization Request ---->|               | |
       |        |       + t(code_verifier), t_m  | | Authorization | |
       |        |                                | |    Endpoint   | |
       |        |<-(B)---- Authorization Code -----|               | |
       |        |                                | +---------------+ |
       | Client |                                |                   |
       |        |                                | +---------------+ |
       |        |--(C)-- Access Token Request ---->|               | |
       |        |          + code_verifier       | |    Token      | |
       |        |                                | |   Endpoint    | |
       |        |<-(D)------ Access Token ---------|               | |
       +--------+                                | +---------------+ |
                                                 +-------------------+

                     Figure 2: Abstract Protocol Flow

Hope that makes sense! For more reading information, Okta's docs do a great job describing it -> [Auth Code Flow + PKCE](https://developer.okta.com/authentication-guide/implementing-authentication/auth-code-pkce.html).

**Comment by skeer00** [comment]
Thanks for your answer. We are following Resource Owner Password and using SDK (.login().start(view: ...) to get the accesstoken and refresh token. So when the access token is expired how can we get a new access token? Is there any SDK methods for that purpose? I saw one method OktaAuth.refresh(), but I could not find any examples for that. Could you please help me on this?

**Comment by jmelberg-okta** [comment]
@skeer00,

As noted in the [`README`](https://github.com/okta/okta-sdk-appauth-ios#refresh-a-token), you can simply call `OktaAuth.refresh()` to get a new `accessToken`:
```swift
// Refresh the token
OktaAuth.refresh()

// Introspect the token to ensure it is now valid
let token = OktaAuth.tokens.get(forKey: "accessToken")
OktaAuth
    .introspect()
    .validate(token: token) {
        response, error in
            if error != nil { print("Error: \(error!)") }
            if let isActive = response { print("Is token valid? \(isActive)") }
    }
```

**Comment by wdawson** [comment]
@skeer00 just to reiterate and make sure it's clear, the resource-owner password flow (with client secret) is less secure than the authorization code flow with PKCE. Is there a reason you're using resource-owner password?

**Comment by skeer00** [comment]
@jmelberg-okta This for providing more native experience.
