### ISSUE TITLE
Add `idp=` parameter support for AppAuth

### ISSUE THREAD

**Issue by omgitstom** [okta/okta-sdk-appauth-ios#32]
As a developer, I want to trigger Okta to log in the user with Google using the `idp` parameter with app auth, so my user doesn't need to view a page to just click on another button

**Comment by jmelberg-okta** [comment]
More generally, we should allow customization of `additionalParams` when building the `/authorize` request.

**Comment by jmelberg-okta** [comment]
This has been resolved in the [newest release](https://github.com/okta/okta-sdk-appauth-ios/releases/tag/1.0.0).
