### ISSUE TITLE
SFAuthenticationSession popup

### ISSUE THREAD

**Issue by WillChilcutt** [okta/okta-sdk-appauth-ios#61]
Hello,

On iOS 11+ There is a popup that says "<Your App> Wants to Use '<Login provider URL>' to Sign in".

This is in relation to **SFAuthenticationSession** which has the following footnote at https://developer.apple.com/documentation/safariservices/sfauthenticationsession

> If an application uses SFAuthenticationSession, users are prompted by a dialog to give explicit consent, allowing the application to access the website's data in Safari. When the webpage is presented, it runs in a separate process, so the user and web service are guaranteed that the app has no way to gain access to the user’s credentials. Instead, the app gets a unique authentication token.

Is there any workaround we could have to get around having this **UIAlertView** pop up that is very breaking in user experience with logging in?

Thanks

**Comment by jmelberg-okta** [comment]
Hey @WillChilcutt,

I've been following our underlying library AppAuth's implementation of this [here](https://github.com/openid/AppAuth-iOS/issues/200), where the change has already been merged into `master`. Although, this has yet to be released in a new version and pulled into this lib.

This isn't a change we're likely to extend into our wrapper library, as developers will lose SSO support. If you'd like to get this plugged in immediately into your application, I'd suggest taking a look at [this comment](https://github.com/openid/AppAuth-iOS/issues/200#issuecomment-364610027).

**Comment by WillChilcutt** [comment]
Hi @jmelberg-okta. Thanks for the quick response, suggestions and insight into the issue. I'll mark this as closed as the framework won't likely be changing it.

Thanks,

Will
