### ISSUE TITLE
In Swift 3, unwrapping redirectUri causes crash

### ISSUE THREAD

**Issue by jameswfang** [okta/okta-sdk-appauth-ios#67]
```
                // Build the Authentication request
                let request = OIDTokenRequest(
                           configuration: oidConfig,
                               grantType: grantType,
                       authorizationCode: authCode,
                             redirectURL: URL(string: redirectUri)!,
                                clientID: clientId,
                            clientSecret: clientSecret,
                                  scopes: Utils.scrubScopes(config["scopes"]),
                            refreshToken: refreshToken,
                            codeVerifier: nil,
                    additionalParameters: additionalParams
                )
```

```
                // Build the Authentication request
                let request = OIDAuthorizationRequest(
                           configuration: oidConfig,
                                clientId: clientId,
                                  scopes: Utils.scrubScopes(config["scopes"]),
                             redirectURL: URL(string: redirectUri)!,
                            responseType: OIDResponseTypeCode,
                    additionalParameters: Utils.parseAdditionalParams(config)
                )
```

Change to:
`redirectURL: URL(string: redirectUri.addingPercentEncoding(withAllowedCharacters: NSCharacterSet.urlQueryAllowed)!)!,`

**Comment by jmelberg-okta** [comment]
Hey @jameswfang - Did you encounter this issue because you weren't providing a `redirectUri` in your plist? Our README is pretty explicit that this is a required value, but I'm curious how you encountered this.

**Comment by jameswfang** [comment]
@jmelberg-okta I did set the redirectUri to com.oktapreview.{Okta org}:/callback as recommended in the Readme.md.

Here is a screenshot of the stack trace:
![image](https://user-images.githubusercontent.com/24444212/42650807-40a579fa-85c2-11e8-828a-a9fa3bdc8ebc.png)

**Comment by jmelberg-okta** [comment]
Hey @jameswfang,
 
It looks like you have a malformed character in your `redirectUri` value: `\t`. That should explain why unwrapping the value is throwing an error.

This does bring up a valid concern on unwrapping vars - something we're going to be looking at in a future release. Ideally we should validate all values are stripped for whitespace before they're attempted for use.

Can you try removing the `\t` to see if that solves your issue?

**Comment by jameswfang** [comment]
@jmelberg-okta That was it, thanks!
