### ISSUE TITLE
iat validation without leeway is wrong

### ISSUE THREAD

**Issue by sergio83** [okta/okta-sdk-appauth-ios#69]
The **OktaJWTVerifier.isIssuedInFuture** return true if the iat is valid.

On **OktaJWT.swift:** is returning error when the iat is valid
**Current code:**
`   
if OktaJWTVerifier.isIssuedInFuture(jwt.payload.issuedAt, leeway: self.validatorOptions["leeway"] as? Int) {
                throw OktaJWTVerificationError.IssuedInFuture
            }
`

**Fixed Code:**
`    
if **!**OktaJWTVerifier.isIssuedInFuture(jwt.payload.issuedAt, leeway: self.validatorOptions["leeway"] as? Int) {
                throw OktaJWTVerificationError.IssuedInFuture
            }
`

**Comment by jmelberg-okta** [comment]
Hi @sergio83 -

Apologies if I'm not understanding this issue, but looking at the [`OktaJWT` source](https://github.com/okta/okta-ios-jwt/blob/d8a5704faaf0b13d3dd21d8befd1a6829e7f252f/OktaJWT/JWTVerifier.swift#L109-L125) you're referring to, we're evaluating this correctly:

1. If no `leeway` is provided, we compare the current time with the token time:
    ```swift
    if (now < iat) {
      // Token is issued in the future and throw an IssuedInFuture error
    }
    ```
2. If `leeway` is provided, add that to the current time:
    ```swift
    if (now + leeway < iat) {
      // Token is issued in the future and throw an IssuedInFuture error
    }
    ```

If your system clock is **behind** (what `leeway` for `iat` assumes) this will ensure that your application can accept the token.

Based on your proposed solution above, we'd actually do the **opposite** of what we'd like to do, and throw an error when the token is **not** issued in the future.
