### ISSUE TITLE
The client secret is not send

### ISSUE THREAD

**Issue by sergio83** [okta/okta-sdk-appauth-ios#70]
On the class **OktaAuth.swift**, method **authCodeFlow**,  when create the OIDAuthorizationRequest is not added the clientSecret.

To fix it, you have to get it:
let clientSecret = config["clientSecret"]

and then:
OIDAuthorizationRequest(configuration: oidConfig,
                                clientId: clientId,
                                **clientSecret: clientSecret,**
                                  scopes: Utils.scrubScopes(config["scopes"]),.....

**Comment by jmelberg-okta** [comment]
Hey @sergio83 - This is the intended behavior.

When using the Authorization Code flow, we're utilizing [PKCE](https://tools.ietf.org/html/rfc7636) for client authentication, not the client secret. This is the suggested method for implementing OAuth 2.0 for native applications.

If you're looking to use the Resource Owner Password Flow, which will require the `clientId` and `clientSecret` to be provided, please see the instructions for username/password authentication [here](https://github.com/okta/okta-sdk-appauth-ios#authorization).
