### ISSUE TITLE
Build demo of native login

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-appauth-ios#78]
Some customers can't use the AppAuth pattern (opening a browser and handling a callback to the app) because they want to have complete control over the UI/UX of the login experience. In other words, they want to have a totally native, in-app UI for login. The SDK will need a number of improvements to support this.

Before building the full solution, we should build a demo to validate that the proposed flow against Okta makes sense. This demo does not need to use the existing SDK.

Here is the login flow:

1. Use an HTTP client to POST to the Authentication API. Send a username and password to [perform primary authentication](https://developer.okta.com/docs/api/resources/authn#primary-authentication-with-public-application). The Authentication API will [return a `sessionToken`](https://developer.okta.com/docs/api/resources/authn#response-example-for-primary-authentication-with-public-application-success).
2. Construct a request for the [Authorization Code + PKCE flow](https://developer.okta.com/authentication-guide/implementing-authentication/auth-code-pkce). Include an optional parameter: `&sessionToken=` with the value of the sessionToken from the Authentication API response. Include scope `offline_access` to request a refresh token.
3. If the response has HTTP status code 302, parse the response headers to get the code from the Location header: `{redirectUri}?code=foobar`
4. Construct the [code exchange request](https://developer.okta.com/authentication-guide/implementing-authentication/auth-code-pkce#3-exchanging-the-code-for-tokens) to get access, ID, and refresh tokens in the app.

**Comment by olexiylebedyev-okta** [comment]
Demo app published here: https://github.com/allebedew/okta-login-ios
