### ISSUE TITLE
Support for additional parameters in token exchange request

### ISSUE THREAD

**Issue by govindprasadgupta** [okta/okta-sdk-appauth-ios#79]
File: OIDAuthState.h
 Method: OIDTokenRequest *tokenExchangeRequest =
                                   [authorizationResponse tokenExchangeRequest];

Kindly provide support for additionalParameters. Everywhere value is passed as nil.

**Comment by nbarbettini** [comment]
@govindprasadgupta What are the additional parameters you need to send?

**Comment by nbarbettini** [comment]
We are adding support for sending additional parameters to the [/authorize endpoint](https://developer.okta.com/docs/api/resources/oidc#authorize) in #90. If you also need to pass additional params to the /token endpoint, please reopen this issue and let us know!
