### ISSUE TITLE
Pass additional parameters to browser sign-in

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-appauth-ios#90]
Some developers need to pass additional parameters to the `/authorize` route (browser sign-in), such as:

* A login hint (the `login_hint` parameter, string)
* A `state` value (string)
* Any string name/value pair

Unlike values like `issuer` and `scopes`, these parameters will not be stored in `Okta.plist`. We should make it possible to pass parameters to the browser sign-in method.

**Comment by jmelberg-okta** [comment]
This is already supported via an undocumented `login` method. Will add this to the list of documentation updates in #97.
