### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-appauth-ios#97]
These things are not currently documented:

- [x] How to sign the user out of the app
- [x] How to end the Okta session (after #87) is merged
- [ ] An example of how to get the access token from the tokenManager and use it when making an HTTP call
- [x] How to pass additional parameters to the `/authorize` endpoint
And we need to confirm that these things are removed from documentation
- [x] Anything relating to resource owner password flow/client secret

**Comment by jmelberg-okta** [comment]
@nbarbettini - Similar to other libraries, we should point developers to the quickstart and/or code page on D.O.C for use-case driven code samples.

For this reason, the README updates in #106 are primarily outlining the public API for this library, as opposed to a formal "how-to" guide.
